name: Build and Deploy Comun

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - uses: actions/checkout@v3

      # 2️⃣ Configurar Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          server-id: github         
          settings-path: ${{ github.workspace }}

      # 3️⃣ Build y Deploy del módulo comun
      - name: Build and Deploy Comun
        working-directory: ./P2_COMUN/comun   
        run: mvn clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.COMUN_SA }}  
