name: Build and Deploy Comun

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Set up Maven settings for GitHub Packages
        run: |
          mkdir -p $HOME/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.TOKEN }}</password>
                    </server>
                  </servers>
                </settings>" > $HOME/.m2/settings.xml

      - name: Update version dynamically
        working-directory: ./comun
        run: mvn versions:set -DnewVersion=1.0.${{ github.run_number }}-SNAPSHOT

      - name: Build and Deploy Comun
        working-directory: ./comun
        run: mvn clean deploy -DskipTests
